### ISSUE TITLE
MAPS - Desenvolver mapa

### ISSUE THREAD

**Issue by TolbyOwl** [EricAngelo22/Projeto-Uninove#4]
A cliente(Patrícia Braga): "Solicito um recurso de fácil visualização da localização de meu escritório no Maps, para que os usuários possam ter a praticidade e reconhecimento da localização."

-Desenvolver mapa do Google Maps que possa ser interagido pelo usuário no site em formato HTML e CSS.
 -O mesmo vai facilitar a visualização de localização do cliente e seu consultório/endereço.

Responsável:
-Winicius

**Comment by WiniciusAlencar** [comment]
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <title>Site com Google Maps</title>
</head>
<body>
    <div class="mapBox">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3675.1210171261755!2d-47.031660099999996!3d-22.9089068!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94c8cf10885d6e69%3A0x7ce47965043b81a9!2sR.%20Jos%C3%A9%20Jorge%20Far%C3%A1h%2C%20222%20-%20Parque%20Nova%20Campinas%2C%20Campinas%20-%20SP%2C%2013100-081!5e0!3m2!1spt-BR!2sbr!4v1726360251120!5m2!1spt-BR!2sbr"  width="800" height="600" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
</body>
</html>

**Comment by WiniciusAlencar** [comment]
/<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <title>Site com Google Maps</title>
</head>
<body>
    <div class="mapBox">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3675.1210171261755!2d-47.031660099999996!3d-22.9089068!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94c8cf10885d6e69%3A0x7ce47965043b81a9!2sR.%20Jos%C3%A9%20Jorge%20Far%C3%A1h%2C%20222%20-%20Parque%20Nova%20Campinas%2C%20Campinas%20-%20SP%2C%2013100-081!5e0!3m2!1spt-BR!2sbr!4v1726360251120!5m2!1spt-BR!2sbr"  width="800" height="600" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
</body>
</html>
